# -*- coding: utf-8 -*-
"""hungry.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifsazn_T7hWH6oJ3CDYNjo-GmIKdj3zw
"""

hungry = input("are you hungry?")
if hungry == 'Yes':
  print("eat pizza")

else:
  thristy = input("are u thristy")
  if thristy == 'Yes':
    print('drink water')
    print('drink soda')

